/**
 * Default check item configuration.
 * Used when config/checks.json doesn't exist or as a starting template.
 */

import type { ChecksConfig } from "../types";

export const DEFAULT_CHECKS_CONFIG: ChecksConfig = {
  version: 1,
  checks: [
    // ── C-Rank Checks (target: 95%) ──
    {
      id: "C-001",
      rank: "C",
      name: "Drawing number present",
      nameJa: "図番の記載有無",
      description: "Verify that the drawing number field in the title block is filled and legible",
      enabled: true,
      categories: "*",
      requiredRegions: ["title_block"],
      judgmentMethod: "rule+llm",
      promptTemplate: "prompts/title-block-field.md",
      promptVariables: { fieldName: "drawing_number", fieldNameJa: "図番" },
      passCriteria: "Drawing number field is non-empty and legible",
      targetAccuracy: 0.95,
    },
    {
      id: "C-002",
      rank: "C",
      name: "Part name present",
      nameJa: "品名の記載有無",
      description: "Verify that the part name field in the title block is filled",
      enabled: true,
      categories: "*",
      requiredRegions: ["title_block"],
      judgmentMethod: "rule+llm",
      promptTemplate: "prompts/title-block-field.md",
      promptVariables: { fieldName: "part_name", fieldNameJa: "品名" },
      passCriteria: "Part name field is non-empty and legible",
      targetAccuracy: 0.95,
    },
    {
      id: "C-003",
      rank: "C",
      name: "Revision/version present",
      nameJa: "版数の記載有無",
      description: "Verify that the revision or version number is present in the title block",
      enabled: true,
      categories: "*",
      requiredRegions: ["title_block"],
      judgmentMethod: "rule+llm",
      promptTemplate: "prompts/title-block-field.md",
      promptVariables: { fieldName: "revision", fieldNameJa: "版数" },
      passCriteria: "Revision/version field is present",
      targetAccuracy: 0.95,
    },
    {
      id: "C-004",
      rank: "C",
      name: "Material specification present",
      nameJa: "材質の記載有無",
      description: "Verify that material/material grade is specified in the title block or notes",
      enabled: true,
      categories: "*",
      requiredRegions: ["title_block"],
      judgmentMethod: "rule+llm",
      promptTemplate: "prompts/title-block-field.md",
      promptVariables: { fieldName: "material", fieldNameJa: "材質" },
      passCriteria: "Material specification is present",
      targetAccuracy: 0.95,
    },
    {
      id: "C-005",
      rank: "C",
      name: "Color specification present",
      nameJa: "色の記載有無",
      description: "Verify that the color or finish is specified (if applicable)",
      enabled: true,
      categories: ["Housing", "Cover", "Lens", "Panel"],
      requiredRegions: ["title_block", "notes_area"],
      judgmentMethod: "rule+llm",
      promptTemplate: "prompts/title-block-field.md",
      promptVariables: { fieldName: "color", fieldNameJa: "色" },
      passCriteria: "Color/finish specification is present",
      targetAccuracy: 0.95,
    },
    {
      id: "C-006",
      rank: "C",
      name: "Recycled material prohibition noted",
      nameJa: "再生材使用不可の記載",
      description: "Check for notation about recycled material usage prohibition",
      enabled: true,
      categories: "*",
      requiredRegions: ["notes_area"],
      judgmentMethod: "rule+llm",
      promptTemplate: "prompts/required-notation.md",
      promptVariables: {
        notationType: "recycled_material_prohibition",
        notationJa: "再生材の使用不可",
      },
      passCriteria: "Recycled material prohibition or allowance is noted",
      targetAccuracy: 0.95,
    },
    {
      id: "C-007",
      rank: "C",
      name: "Environmental regulation compliance noted",
      nameJa: "環境管理物質管理規定の記載",
      description: "Check for environmental substance management regulation reference",
      enabled: true,
      categories: "*",
      requiredRegions: ["notes_area"],
      judgmentMethod: "rule+llm",
      promptTemplate: "prompts/required-notation.md",
      promptVariables: {
        notationType: "environmental_regulation",
        notationJa: "環境管理物質管理規定",
      },
      passCriteria: "Environmental regulation reference is present",
      targetAccuracy: 0.95,
    },
    {
      id: "C-008",
      rank: "C",
      name: "Note numbering continuity",
      nameJa: "注記番号飛び",
      description: "Verify that note numbers are sequential with no gaps or duplicates",
      enabled: true,
      categories: "*",
      requiredRegions: ["notes_area"],
      judgmentMethod: "rule+llm",
      promptTemplate: "prompts/note-numbering.md",
      passCriteria: "Note numbers are sequential without gaps",
      targetAccuracy: 0.95,
    },
    {
      id: "C-009",
      rank: "C",
      name: "Revision symbol consistency",
      nameJa: "改訂記号と版数の一致",
      description: "Verify that the latest revision symbol matches the title block version",
      enabled: true,
      categories: "*",
      requiredRegions: ["title_block", "revision_table"],
      judgmentMethod: "rule+llm",
      promptTemplate: "prompts/revision-consistency.md",
      passCriteria: "Latest revision symbol matches title block version",
      targetAccuracy: 0.95,
    },
    {
      id: "C-010",
      rank: "C",
      name: "Gate method/position/count specified",
      nameJa: "ゲート方式・位置・取り数の記載",
      description: "For molded parts: verify gate method, position, and cavity count are noted",
      enabled: true,
      categories: ["Housing", "Cover", "Connector", "Bracket"],
      requiredRegions: ["notes_area", "projection_view"],
      judgmentMethod: "rule+llm",
      promptTemplate: "prompts/required-notation.md",
      promptVariables: {
        notationType: "gate_specification",
        notationJa: "ゲート方式・位置・取り数",
      },
      passCriteria: "Gate method, position, and cavity count are specified",
      targetAccuracy: 0.95,
    },

    // ── B-Rank Checks (target: 90%) ──
    {
      id: "B-001",
      rank: "B",
      name: "Dimension overlap with outlines",
      nameJa: "寸法線と外形線の重なり",
      description: "Check if dimension text or lines overlap with part outlines or other dimensions",
      enabled: true,
      categories: "*",
      requiredRegions: ["projection_view", "dimension_area"],
      judgmentMethod: "rule+llm",
      promptTemplate: "prompts/dimension-overlap.md",
      passCriteria: "No dimension text or leader lines overlap with part outlines",
      targetAccuracy: 0.90,
    },
    {
      id: "B-002",
      rank: "B",
      name: "Outermost dimensions present",
      nameJa: "最外寸法の有無",
      description: "Verify that overall/outermost dimensions are present for each view",
      enabled: true,
      categories: "*",
      requiredRegions: ["projection_view"],
      judgmentMethod: "rule+llm",
      promptTemplate: "prompts/outermost-dims.md",
      passCriteria: "Overall width and height dimensions are present",
      targetAccuracy: 0.90,
    },
    {
      id: "B-003",
      rank: "B",
      name: "Duplicate/redundant dimensions",
      nameJa: "二重寸法・重複寸法",
      description: "Check for duplicate or redundant dimension annotations",
      enabled: true,
      categories: "*",
      requiredRegions: ["projection_view"],
      judgmentMethod: "rule+llm",
      promptTemplate: "prompts/duplicate-dims.md",
      passCriteria: "No duplicate or redundant dimensions found",
      targetAccuracy: 0.90,
    },
    {
      id: "B-004",
      rank: "B",
      name: "Filename matches title block",
      nameJa: "ファイル名と表題欄の一致",
      description: "Verify that the file name matches the drawing number and part name in the title block",
      enabled: true,
      categories: "*",
      requiredRegions: ["title_block"],
      judgmentMethod: "rule+llm",
      promptTemplate: "prompts/filename-match.md",
      passCriteria: "Filename components match title block drawing number and part name",
      targetAccuracy: 0.90,
    },
    {
      id: "B-005",
      rank: "B",
      name: "Tolerance notation consistency",
      nameJa: "普通許容差の記載と斜線の一致",
      description: "Check that general tolerance notation is present and consistent with slash marks",
      enabled: true,
      categories: "*",
      requiredRegions: ["title_block", "notes_area"],
      judgmentMethod: "rule+llm",
      promptTemplate: "prompts/tolerance.md",
      passCriteria: "General tolerance is specified and slash marks are consistent",
      targetAccuracy: 0.90,
    },

    // ── A-Rank Checks (target: 70% WANT) ──
    {
      id: "A-001",
      rank: "A",
      name: "Missing dimensions on functional features",
      nameJa: "機能部位の寸法抜け",
      description: "Identify functional features (clips, contact surfaces, bosses) and verify all have dimensions",
      enabled: true,
      categories: ["Housing", "Cover", "Bracket", "Connector"],
      requiredRegions: ["projection_view", "dimension_area"],
      judgmentMethod: "rag+llm",
      promptTemplate: "prompts/missing-dims.md",
      passCriteria: "All identified functional features have associated dimensions",
      targetAccuracy: 0.70,
    },
    {
      id: "A-002",
      rank: "A",
      name: "Gate position vs stress-critical areas",
      nameJa: "ゲート位置と強度懸念部",
      description: "Check if gate position could cause weld lines in stress-critical areas",
      enabled: true,
      categories: ["Housing", "Cover", "Bracket"],
      requiredRegions: ["projection_view", "notes_area"],
      judgmentMethod: "rag+llm",
      promptTemplate: "prompts/gate-position.md",
      passCriteria: "Gate position does not create weld lines in stress-critical areas",
      targetAccuracy: 0.70,
    },
    {
      id: "A-003",
      rank: "A",
      name: "Thin-wall/slot detection",
      nameJa: "極端な薄肉部・長穴形状の検出",
      description: "Detect extremely thin walls or long slots and verify appropriate care annotations",
      enabled: true,
      categories: ["Housing", "Cover", "Bracket"],
      requiredRegions: ["projection_view"],
      judgmentMethod: "rag+llm",
      promptTemplate: "prompts/thin-wall.md",
      passCriteria: "No unaddressed thin-wall or long-slot concerns",
      targetAccuracy: 0.70,
    },
  ],
};
